// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiGQhXrUjba1HuKR8w3AErpediBNi253w',
    appId: '1:106512992195:web:f60890eb5b0a18eb181f76',
    messagingSenderId: '106512992195',
    projectId: 'main-f8d39',
    authDomain: 'main-f8d39.firebaseapp.com',
    storageBucket: 'main-f8d39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpPjxbaJBDPhVva9UYXJhi_CYhvFzf4RY',
    appId: '1:106512992195:ios:9e5899db8002422a181f76',
    messagingSenderId: '106512992195',
    projectId: 'main-f8d39',
    storageBucket: 'main-f8d39.firebasestorage.app',
    iosBundleId: 'com.kproduce.slotbooking',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrZXytCJH3ocEKEW98cN1HaZl3gCcvnFw',
    appId: '1:106512992195:android:f5895ad5058651a1181f76',
    messagingSenderId: '106512992195',
    projectId: 'main-f8d39',
    storageBucket: 'main-f8d39.firebasestorage.app',
  );

}